Add example class to template
utopia-rise/godot-kotlin-jvm pull request #139
Opened 2021-04-16 12:17 UTC by chippmann

Resolves #136

2021-04-17 00:53 UTC, CedNaru approved these changes

2021-04-17 00:54 UTC, CedNaru requested changes
I would use GD.print instead of println.
Someone  on discord said he was confused because his print didn't show up inside the editor. Only on the cli.

2021-04-18 01:44 UTC, raniejade approved these changes

2021-04-18 07:08 UTC, piiertho approved these changes

2021-04-18 07:57 UTC, CedNaru approved these changes

2021-04-18 08:04 UTC, merged