Hotfix/fix from godot to kotin basis
utopia-rise/godot-kotlin-jvm pull request #142
Opened 2021-04-16 18:00 UTC by piiertho

There several bugs in cpp to kotlin sending:
- Basis data was not set correctly (confusion between axis and elements)
- Variant type for plane was not sent through buffer, which doe not respect protocol.

This adds core types identity tests for cpp to kotlin.

This resolves #132

2021-04-16 18:14 UTC, chippmann approved these changes

2021-04-17 00:30 UTC, CedNaru requested changes
I would make a small change as well to basis:

The kotlin array operator doesn't match the C++ one:

Kotlin return the columns using getAxis.
![image](https://user-images.githubusercontent.com/31470327/115096201-69f16980-9f24-11eb-993c-95c18fbe9205.png)

But CPP returns the rows by using the internal array.
(The 3 vector3 in C++ are put into an array. I can't do that in Kotlin because Array is not primitive which would add an additional instance and indirection in Basis.)

![image](https://user-images.githubusercontent.com/31470327/115096230-7e356680-9f24-11eb-842e-4a9a20d05cfe.png)

2021-04-17 12:06 UTC, piiertho commented
> I would make a small change as well to basis:
> 
> The kotlin array operator doesn't match the C++ one:
> 
> Kotlin return the columns using getAxis.
> ![image](https://user-images.githubusercontent.com/31470327/115096201-69f16980-9f24-11eb-993c-95c18fbe9205.png)
> 
> But CPP returns the rows by using the internal array.
> (The 3 vector3 in C++ are put into an array. I can't do that in Kotlin because Array is not primitive which would add an additional instance and indirection in Basis.)
> 
> ![image](https://user-images.githubusercontent.com/31470327/115096230-7e356680-9f24-11eb-842e-4a9a20d05cfe.png)

For now we follow same as GDScript. I added small tests on get and set of `Vector3` and `Basis` which ensure this convention.

2021-04-18 01:42 UTC, raniejade approved these changes

2021-04-18 09:36 UTC, CedNaru approved these changes

2021-04-18 09:37 UTC, merged