Feature/godot 3.3.0
utopia-rise/godot-kotlin-jvm pull request #174
Opened 2021-04-23 17:13 UTC by piiertho

This updates module to Godot 3.3.
Please test it carefully on your side before we merge it.

2021-04-23 21:09 UTC, chippmann requested changes

2021-04-23 21:09 UTC, chippmann commented on harness/benchmarks/godot-project.csproj
> +<Project Sdk="Godot.NET.Sdk/3.3">
This will not work as the target framework version also need to change IIRC
Once i have mono setup again, I'll push a fix to this PR

2021-04-25 08:30 UTC, chippmann approved these changes

2021-04-25 10:26 UTC, raniejade approved these changes

2021-04-25 10:26 UTC, raniejade commented on docs/src/doc/versioning.md
> +Full version: `0.1.0-3.3.0`
nit: I don't think its scalable to change this documentation every time we bump the engine version. The versions here are an example, so this specific change is unnecessary.

2021-04-25 16:52 UTC, CedNaru approved these changes

2021-04-25 19:17 UTC, merged