Implement new rpc related functionality
utopia-rise/godot-kotlin-jvm pull request #341
Opened 2022-07-15 16:49 UTC by chippmann

This changes our rpc related code to support the changes made in godot.

Namely;
- Drop of rset and any other property related rpc calls and configuration
- New rpc config and config retrieval

This also updates the registration code, code generation and the IDE checks.

2022-08-19 07:58 UTC, piiertho requested changes
Great work !
I have some questions, and new commit on godot master invalidate cpp code.

2022-08-19 07:58 UTC, piiertho commented on harness/tests/src/main/kotlin/godot/tests/FuncRefTest.kt
>      var blubb: Boolean = false
Isn't it missing `@Rpc` annotation ?

2022-08-19 07:58 UTC, piiertho commented on harness/tests/src/main/kotlin/godot/tests/Invocation.kt
> +		name = StringName("TestName") //TODO/4.0: provide convenience wrapper for StringName properties and parameters
You should have an extension method to convert `String` to `StringName`

2022-08-19 07:58 UTC, piiertho commented on harness/tests/src/main/kotlin/godot/tests/rpctests/RpcTests.kt
>      var remoteSyncProperty: Boolean = false
Missing `@Rpc` annotation ?

2022-08-19 07:58 UTC, piiertho commented on kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt
> -    fqName == "kotlin.Unit" -> ClassName("godot.core.VariantType", "NIL")
Not sure why this is removed

2022-08-19 07:58 UTC, piiertho commented on src/kt_class.cpp
> +    while (current) {
With 4.0 you can now use classic for each, like here : https://github.com/utopia-rise/godot-kotlin-jvm/blob/d108e232d4b0599ba53aca3d54ed382e653fdcb2/src/gd_kotlin.cpp#L456

2022-08-19 07:58 UTC, piiertho commented on src/kotlin_script.cpp
>  const Vector<Multiplayer::RPCConfig> KotlinScript::get_rpc_methods() const {
Seems method changed recently: https://github.com/godotengine/godot/commit/ca7d572908c58c587214b8f65bdd4078d0185ab2

2022-10-31 12:47 UTC, chippmann commented
Superseeded by #369

2022-10-31 12:47 UTC, closed without merging