enh: Use DEV_ENABLED definition in cpp code
utopia-rise/godot-kotlin-jvm pull request #475
Opened 2023-07-09 11:23 UTC by piiertho

2023-07-09 13:00 UTC, chippmann requested changes

2023-07-09 13:00 UTC, chippmann commented on src/gd_kotlin.cpp
> +#ifdef DEV_ENABLED
This one i would leave. Helps debugging update issues on published projects

2023-07-12 03:33 UTC, CedNaru submitted a review, later dismissed

2023-08-09 05:49 UTC, chippmann approved these changes

2023-08-09 21:30 UTC, CedNaru approved these changes

2023-08-24 14:04 UTC, merged