Update documentation for godot 4
utopia-rise/godot-kotlin-jvm pull request #476
Opened 2023-07-09 12:45 UTC by chippmann

Resolves #460 and resolves #447.

Updates our documentation for Godot 4.

2023-07-12 03:45 UTC, CedNaru submitted a review, later dismissed

2023-07-16 13:16 UTC, piiertho requested changes

2023-07-16 13:16 UTC, piiertho commented on docs/src/doc/contribution/setup.md
> +1. Clone godot repo with the stable tag you want to develop for (master in this example). `git clone git@github.com:godotengine/godot.git 4.x --recursive`
Should be `4.1-stable`

2023-07-16 16:39 UTC, piiertho approved these changes

2023-07-16 17:52 UTC, merged