Add option to pass arguments to scene JVM
utopia-rise/godot-kotlin-jvm pull request #584
Opened 2024-03-10 12:32 UTC by LukasVykuka

This add new parameter to `godot_kotlin_configuration.json` to pass argument to the JVM, which runs in the scene regardless of whether the scene was launch from editor or from command line.
My use case is possibility of writing Kotlin code and connecting debugger in IntelliJ and at the same time running scene from Godot editor. For example
```
{"max_string_size":512,"vm_type":"jvm","scene_jvm_args":"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"}
```
Also it can be used for any JVM arguments. I will add docs after we agree on parameter name.

2024-03-21 02:49 UTC, CedNaru commented
So the goal is that you can use those JVM argument even when starting the scene from the editor itself instead of having to launch it from command line only with the argument.
So, the arguments written in the configuration JSON are guaranteed to be used for the non editor usages of the project. Given the usage, wouldn't that be better to call it `debug_jvm_args` or similar ?

2024-03-23 09:48 UTC, LukasVykuka commented
I think `debug` is misleading because this parameter can be used to pass any args to JVM (not only to enable debugging) and also can be used in release build of game. So just `jvm_args` can be enough?

2024-03-24 08:01 UTC, piiertho requested changes
Few cpp changes.  
@CedNaru and @chippmann do you remember why we did not use project parameters instead of a json file ?

2024-03-25 04:37 UTC, CedNaru commented
I think it's mostly for convenience. We can easily edit the json before starting the editor, meanwhile using project parameters require to already start the engine (so after reading said parameters) or to edit a much more complex godot file.

2024-03-26 14:18 UTC, chippmann requested changes
LGTM (apart from the arg name. Once that's resolved, I'll happily approve :-) )
Thx a lot!

2024-03-27 05:14 UTC, CedNaru commented
I'm fine `jvm_args`

2024-04-06 19:00 UTC, CedNaru commented
As part of the overhaul of the C++ code, the argument parsing part of the module is currently being completly changed.
To avoid conflict, I am going to add the feature of this PR into mine. #601

2024-04-07 11:42 UTC, LukasVykuka commented
Ok, cool. This PR can be closed, I guess.

2024-04-09 18:35 UTC, closed without merging