GDKotlin Rework: Jvm loading
utopia-rise/godot-kotlin-jvm pull request #602
Opened 2024-04-07 20:30 UTC by CedNaru

2024-04-14 01:56 UTC, CedNaru commented
Tested on Windows with the following configurations:
- Editor with Embedded JVM
- Editor with JAVA_HOME only
- Export with JVM
- Export with Graal native image

2024-04-14 01:58 UTC, CedNaru commented
Tested the Export on Android.

2024-04-14 12:00 UTC, chippmann requested changes
Tested on linux:
- Editor with `JAVA_HOME` -> also with reloading
- Editor with embedded jvm -> also with reloading
- Debug export templates embedded jvm
- Release export templates embedded jvm
- Debug export templates graaal vm native image
- Release export templates graaal vm native image

Apart from the encountered issues regarding configuration file parsing and exporting mentioned on discord, everything seems to work well.

Awesome job!

Will continue testing throughout the day on a pet project

2024-04-14 15:34 UTC, chippmann approved these changes

2024-04-22 16:08 UTC, piiertho commented on src/lifecycle/class_loader.cpp
> +    jni ::JClass class_loader_cls {env.find_class("dalvik/system/DexClassLoader")};
typo: `jni ::JClass` => `jni::JClass`

2024-04-22 16:15 UTC, piiertho commented on src/lifecycle/paths.h
> +static constexpr const char* GRAAL_NATIVE_IMAGE_FILE {"usercode.so"};
This is weird to define a path to a shared library on iOS

2024-04-22 18:59 UTC, CedNaru commented on src/lifecycle/jvm_options.cpp
> +    String suspend;
Good catch, I just copied that part from the previous code, didn't think of changing it.

2024-04-23 10:49 UTC, chippmann commented
Tested on macos x86_64:
With graalvm native image:
- editor
- export release
- export debug

2024-04-23 10:50 UTC, piiertho approved these changes

2024-04-23 14:22 UTC, merged