Feature/ios/update to graal 23
utopia-rise/godot-kotlin-jvm pull request #619
Opened 2024-04-25 16:43 UTC by piiertho

This updates iOS export to JDK 21 using graalVM native image 23.1.3.  
JDK libraries used for iOS comes from [this repo](https://github.com/utopia-rise/ios-graal-jdk-21).  

This removes [ios_graal_fix.c](https://github.com/utopia-rise/godot-kotlin-jvm/blob/master/kt/plugins/godot-gradle-plugin/src/main/resources/godot/gradle/ios/ios_graal_fix.c).  
This simplifies creation of `usercode.a`.  
This updates to GUT `9.2.1`.  
This makes GUT scene the main project scene.

2024-04-26 11:46 UTC, CedNaru submitted a review, later dismissed

2024-04-29 07:28 UTC, chippmann requested changes
On top of the requested changes, I'd appreciate a small step by step guide on what to change where to update the jvm version for ios exports.

We have some constants defined now with this PR which all need to be updated.
Cap files and configs also need to be updated.
The build process of the jvm is written nicely in that repo so that one is clear. But for me what is missing is the steps needed to be done in this repo.

Other than that. Great work!

2024-04-29 07:28 UTC, chippmann commented on kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/graal/GraalProjectExtensions.kt
> +    outputFile.writeBytes(resource.readAllBytes())
I would use an input and output stream here

2024-04-29 07:28 UTC, chippmann commented on kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/graal/ios/downloadIOSJdkStaticLibraries.kt
> +                val iosGraalJdkReleaseBaseLink = "https://github.com/utopia-rise/ios-graal-jdk-21/releases/download/v23.1.3-21-b33/"
Could we move this download url (or at least the version) to the `gradle/[libs.versions.toml](https://github.com/utopia-rise/godot-kotlin-jvm/blob/master/kt/gradle/libs.versions.toml)` and use it through the build props (https://github.com/utopia-rise/godot-kotlin-jvm/blob/a4c5385efb08621d19a29f0db3cc61b132b2fc54/kt/plugins/godot-gradle-plugin/build.gradle.kts#L42)
Like we do for our own version and the kotlin version

2024-04-29 07:28 UTC, chippmann commented on kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/graal/ios/downloadIOSJdkStaticLibraries.kt
> +                    libJavaFile.writeBytes(URL("$iosGraalJdkReleaseBaseLink/$libJavaFileName").readBytes())
Isn't it possible to use an input/output stream here?

2024-04-29 07:28 UTC, chippmann commented on kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/graal/ios/downloadIOSJdkStaticLibraries.kt
> +                    libJvmFile.writeBytes(URL("$iosGraalJdkReleaseBaseLink/$libJvmFileName").readBytes())
Isn't it possible to use an input/output stream here?

2024-04-29 07:28 UTC, chippmann commented on src/kotlin_editor_export_plugin.cpp
> +        String base_ios_jdk_dir {base_ios_build_dir.path_join("ios-jdk/21/")};
Could we move this constant (the version) to a constants place?

2024-04-29 17:03 UTC, chippmann submitted a review, later dismissed

2024-04-29 21:33 UTC, CedNaru approved these changes

2024-05-01 14:25 UTC, CedNaru commented on docs/src/doc/user-guide/exporting.md
> +With this export you don't have a choice regarding JVM version you use. Please use GraalVM 23.1.3.
I remember older versions being harder to find whenever a new version comes out. We should add a direct link in the doc to help people who wish to install it.

2024-05-04 11:48 UTC, CedNaru commented on docs/src/doc/knowledge-base/update-ios-jdk.md
> +- Change iOS JDK versions and CAP cache versions in `libs.versions.toml` of this project.
Also should write that the link to the right GraalVM in the doc has to be updated.

2024-05-06 13:03 UTC, chippmann approved these changes

2024-05-06 13:03 UTC, chippmann commented on kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/setupTasks.kt
> +import godot.gradle.tasks.graal.ios.*
I'd prefer single name imports but its ok for me if you don't change that here.

2024-05-06 13:04 UTC, CedNaru approved these changes

2024-05-06 13:39 UTC, merged