fix(doc): place update ios jdk contribution guide to the right place
utopia-rise/godot-kotlin-jvm pull request #623
Opened 2024-05-07 18:22 UTC by piiertho

2024-05-08 06:04 UTC, chippmann submitted a review, later dismissed

2024-05-08 06:07 UTC, CedNaru requested changes
You created a new file, the one at the wrong place was not deleted/moved so it means we would have 2 of them on the master if we merge like this.
Also this new files misses the part mentioning you have to update the download link to GraalVM when updating.

2024-05-12 15:40 UTC, chippmann approved these changes

2024-05-12 18:40 UTC, CedNaru approved these changes

2024-05-13 07:24 UTC, merged