Update setup documentation in contribution guide
utopia-rise/godot-kotlin-jvm pull request #639
Opened 2024-05-17 09:23 UTC by gabryon99

Expanded the instructions in the setup.md contribution guide. The update includes more detailed information for checking Java installation, clarifies branch tagging for Godot cloning, and provides better guidance for building the engine and samples.

2024-05-18 10:16 UTC, piiertho approved these changes

2024-05-18 10:49 UTC, chippmann requested changes
Very nice! Thx a lot!

2024-05-18 10:49 UTC, chippmann commented on docs/src/doc/contribution/setup.md
> +./gradlew :tools-common:publishToMavenLocal publishToMavenLocal
Actually it's `./gradlew :tools-common:publishToMavenLocal publishToMavenLocal && ./gradlew publishToMavenLocal -Prelease=true` by now as you need both the library-debug and the library-release

2024-07-25 14:59 UTC, chippmann commented on docs/src/doc/contribution/setup.md
> +./gradlew :tools-common:publishToMavenLocal publishToMavenLocal
```suggestion
./gradlew :tools-common:publishToMavenLocal publishToMavenLocal && ./gradlew publishToMavenLocal -Prelease=true
```

2024-07-28 12:24 UTC, merged