Make signal delegate static to avoid memory allocation
utopia-rise/godot-kotlin-jvm pull request #695
Opened 2024-09-22 04:43 UTC by CedNaru

Implement #694 

I mostly modified the Signal generation so it can create its own delegate. I used the opportunity to split generation into smaller functions. If you want to see the truly new stuff, look at the `SignalGenerationService::generateSignalDelegateCompanion`.

The api generation for signals went from this:
```kt
  public val childEnteredTree: Signal1<Node> by signal("node")
```
to 
```kt
  public val childEnteredTree: Signal1<Node> by Signal1
```

The reason for the change is that the previous method was actually creating a field in the class for the signal (as explained in the link proposal), you can only remove that field if the delegation is done on something none at compile already. This sadly doesn't include inline function. So even if I transform the `signal()` function to
```kt
  inline fun <P0> signal1(p0: String) = Signal1
```
It won't work (I tried, and the bytecode generated still has fields for delegates, even if they all point to the same object).

It doesn't matter that the parameter strings are no longer generated, they were useless anyway. Their only function is to name the user created signals in the entry gen so it can be safely be removed in the api gen.

Note: 
I am not fully satisfied. It makes wrappers way lighter (for example, for Node2D, we will save more than 150 Bytes per instance) but this only applies to wrappers. I didn't find a way to make it work for scripts yet.
The main issue is user created signals need string information (for naming the parameters) from the signal() method, which means we can't directly delegate to the static object and so creates a field.

The only way around it, that I can imagine so far, is to change the way user signals are written.
From
```kt
 @RegisterSignal
 val mySignal: Signal1<Int> by signal("number")
```
to 
```kt
 @RegisterSignal("number")
 val mySignal: Signal1<Int> by Signal1
```
The main issue with this approach is that we need a `vararg string` parameter in the annotation, which doesn't provide any safety regarding the number of require parameters to name. It's error-prone, as we can't rely on a method signature directly.
On top of that, it goes against the project of removing annotation for signals as proposed in #606

2024-09-22 10:20 UTC, chippmann approved these changes

2024-09-22 10:21 UTC, chippmann commented
You proposal for user scripts is IMO not an option. IMO safety is more important for user scripts than saving a few bytes in this case.
For the wrappers though, this PR is perfect

2024-09-22 13:32 UTC, CedNaru commented
Well there is a way to keep safety even for script signals. We just need a @RegisterSignal0, @RegisterSignal1, but it's just cumbersome to use and, again, against what we want to do.
I also was never satisfied about how we use this `signal(string)` method, the string is pure metadata that have no consequence on the code itself, the parameters are not even used by the method, they are only there for the sake of being read by KSP. 
So even the current state is quite dirty imo. But I don't have any idea that would fix it and not be a pain to use.

2024-09-23 11:01 UTC, piiertho commented on kt/api-generator/src/main/kotlin/godot/codegen/services/impl/SignalGenerationService.kt
> +    private class GenericClassNameInfo(
Could be cool to have a toTypeSpec method in this class that does:
```kotlin
TypeSpec
            .classBuilder(className)
            .addTypeVariables(genericTypes)
```

2024-09-23 11:03 UTC, piiertho requested changes

2024-09-23 11:03 UTC, piiertho commented on kt/api-generator/src/main/kotlin/godot/codegen/services/impl/SignalGenerationService.kt
> +                    "return %T<%T, %T> { thisRef, property ->  %T(thisRef, property.name)}",
replace spaces with `·`

2024-09-23 11:04 UTC, piiertho commented on kt/tools-common/src/main/kotlin/godot/tools/common/constants/Packages.kt
> +const val kotlinCoroutinePackage = "$kotlinPackage..coroutines"
Why two dots here ?

2024-09-24 06:52 UTC, piiertho approved these changes

2024-09-24 07:34 UTC, chippmann approved these changes
Approving under the assumption that this will not be released as is.
As discussed on discord, I'm not fond of the reduction in ease of use of user script signal definitions. The requirement of an explicit type declaration is one thing, but the not very descriptive error message for users not familiar with the internal workings of our module is a completely separate topic.
While the memory reduction is important, ease of use is as well.

Hence on discord we agreed on a different signal definition implementation which will be implemented as a follow up PR.

2024-09-24 07:35 UTC, chippmann commented
![image](https://github.com/user-attachments/assets/557281bb-2735-45bc-a9ec-fe947f9c6025)
This is one example of such an error message.

From the error, it's not clear that what is missing is an explicit type declaration `: Signal1<Type>`.
Especially since the provided quick fix options by the IDE are misleading

2024-09-24 07:37 UTC, CedNaru commented on kt/godot-library/src/main/kotlin/godot/gen/godot/core/Signals.kt
> -@Suppress("UNUSED_PARAMETER")
It's defined at the file level now.

2024-09-24 07:47 UTC, merged