Fix template usage
utopia-rise/godot-kotlin-jvm pull request #713
Opened 2024-10-04 05:28 UTC by CedNaru

Currently, the editor is not able to automatically use our templates because there is a mismatch between its name and the name of the template. We have so far build our custom editor using the same "name" as the official godot, which creates a conflict.

I made the changes so that the next release is going to use the name `4.3.stable.jvm.0.11.0`.
We can't change the prefix `4.3-stable` unless we directly Godot files, but we can append anything we want to it, so I picked `jvm.ourcurrentversion`

2024-10-04 06:35 UTC, piiertho approved these changes

2024-10-04 06:56 UTC, chippmann requested changes
Please also add why the warning appears to the docs and possibly link to your proposal as well as part of the explanation.

2024-10-05 17:07 UTC, piiertho commented
Why CI is failing on test export ?

2024-10-06 09:28 UTC, piiertho approved these changes

2024-10-07 07:53 UTC, chippmann submitted a review, later dismissed
One nit. I leave it up to you if you want to change that or not.

2024-10-07 07:53 UTC, chippmann commented on docs/src/doc/user-guide/exporting.md
> +    Downloading our templates from the Godot editor is currently not possible, we opened a [proposal](godotengine/godot-proposals#10894) for it.
I would also indicate that this warning can be ignored safely

2024-10-07 08:58 UTC, merged