Add GenerateEmbeddedJreTask to generate JRE
utopia-rise/godot-kotlin-jvm pull request #740
Opened 2024-11-03 15:47 UTC by chippmann

Resolves https://github.com/utopia-rise/godot-kotlin-jvm/issues/163

2024-11-03 15:50 UTC, chippmann commented
I opted against implementing more sophisticated tasks like an export task (like we have for the harness/tests project) as these are highly project specific and not hard to implement. Hence in my opinion, it's not worth shipping such tasks as part of our project

2024-11-03 17:40 UTC, CedNaru requested changes
We should probably add a new task in the godot editor plugin to generate it as well, right next to the Kotlin project generation.

2024-11-03 17:40 UTC, CedNaru commented on kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/GenerateEmbeddedJreTask.kt
> +    var outputDir: String = "jvm/jre-${getArch()}-${getOs()}"
Wonder if we should declare the jvm directory path in the tool-common directory, to avoid hardcoding it here.

2024-11-03 17:40 UTC, CedNaru commented on kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/GenerateEmbeddedJreTask.kt
> +    var javaHome: String = System.getProperty("java.home")
Can we potentially use the JVM running the gradle task if JAVA_HOME is not set ? Also can we make sure it's at least 11 ?

2025-03-10 10:07 UTC, chippmann commented on kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/GenerateEmbeddedJreTask.kt
> +    var outputDir: String = "jvm/jre-${getArch()}-${getOs()}"
done

2025-03-10 10:09 UTC, chippmann commented on kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/GenerateEmbeddedJreTask.kt
> +    var javaHome: String = System.getProperty("java.home")
JAVA_HOME selection done.
The check if we're on java 11 is needless imo as jlink was introduced in java 9 and we simply set the requirement for java 11 as it was the next lts release after 9
if the user uses an older java version than java 11 i think he cannot build the project anyways

2025-03-10 10:11 UTC, chippmann commented
> We should probably add a new task in the godot editor plugin to generate it as well, right next to the Kotlin project generation.

I'd like to do that in a separate PR as I'd like to rework how the editor plugin executes gradle tasks as now we're executing more than just the build task

2025-03-10 10:12 UTC, CedNaru commented
I was talking about the Godot editor plugin, but sure it can also be a different PR.

2025-03-10 10:36 UTC, chippmann commented
> I was talking about the Godot editor plugin, but sure it can also be a different PR.

I did as well. I'd like to rewrite the build manager to be more generic in regards to gradle task execution

2025-03-17 03:08 UTC, CedNaru approved these changes

2025-04-21 12:19 UTC, merged