Small GC refactor
utopia-rise/godot-kotlin-jvm pull request #99
Opened 2021-03-07 03:28 UTC by CedNaru

Fix #72 

This PR slightly changes the GC with the following:
-For Reference and NativeCoreType instances, we now use ReferenceQueue. The JVM GC automatically fill this Queue when an instance is freed. We don't need to manually check every entry in the HashMap.
-The rate of the Thread is not fixed anymore and can dynamically change during runtime between 0ms and 2s. The rate is adjusted for each iteration (+- 100ms)
-In order to not release too much memory at once, a maximum number of References can be free every iteration (256 for now). Don't be afraid of having objects added to the queue faster than we can process them. If it comes to this, the rate is quickly going to be set to 0.
-Same for Objects, we check at most 20% of the objects (minimum of 256 as well in case there is a small number of them). Simple for now, but it's going to be replaced at some point by a young/old generation design.

All the numbers are constants in the GC for now. We can easily tweak the numbers if we wish.
Maybe it will be a good idea to be able to configure that when launching the JVM instead of having constants.

![image](https://user-images.githubusercontent.com/31470327/110227964-85b52900-7efd-11eb-85de-f6ad13cdaddb.png)

2021-03-07 10:28 UTC, chippmann requested changes
Really nice work!
Few minor comments.

2021-03-07 10:29 UTC, chippmann commented
No hickups anymore on my machine as well.
Hotspot looks great as well!
![1](https://user-images.githubusercontent.com/22662033/110236841-612a7280-7f38-11eb-8b10-d486bad9c072.png)
![2](https://user-images.githubusercontent.com/22662033/110236842-625b9f80-7f38-11eb-87cc-db653905e1f3.png)

2021-03-07 18:05 UTC, CedNaru commented on kt/godot-runtime/src/main/kotlin/godot/core/memory/ReferenceWeakReference.kt
> +internal class ReferenceWeakReference(
I don't have use of it as a data class. It's just a child of WeakReference.

2021-03-09 10:43 UTC, piiertho commented
Found the problem.
GC is just not started, this explains why this performs really better on cpu :)

2021-03-10 07:04 UTC, raniejade approved these changes

2021-03-10 09:47 UTC, piiertho approved these changes
Few remarks, can be done in the new branch, not blocking for merging

2021-03-10 09:47 UTC, piiertho commented on kt/godot-runtime/src/main/kotlin/godot/core/GarbageCollector.kt
> +        if (ktObject != null) {
Here there should be a warning about inverting if and return.

2021-03-10 09:47 UTC, piiertho commented on kt/godot-runtime/src/main/kotlin/godot/core/GarbageCollector.kt
> +package godot.core
I suggest to add suppress warning for methods used from CPP.

2021-03-11 09:08 UTC, chippmann approved these changes

2021-03-12 02:12 UTC, merged